### ISSUE TITLE
Compiling errors when using the command

### ISSUE THREAD

**Issue by WilliamWangPeng** [Gilaad-Elstein/scratch3D#1]
HI dear author,  
    It's truly a honor to write a letter to you,  I'm building your project nowadays and found the error when building as following, I wonder if there is a chance that you know the reason? :)

![image](https://user-images.githubusercontent.com/51076736/116841446-d1d5ce80-ac0b-11eb-864b-495f4fe3995a.png)

thank you  
best regards to you  
William

**Comment by Gilaad-Elstein** [comment]
Hello

I'm sorry, I've not had that error myself.

Did you clone and build the Raylib library? It not, that's the issue right
there, you need that to run this project.

Otherwise I can only suggest you try and run a demo project of raylib and
work out the kinks in building it as dependency for a project, then apply
what you learn to building this project.

Good luck!
